export {default as Header} from 'components/Header'
export {default as Setting} from 'components/Setting'
export {default as History} from 'components/History'
export {default as Navi} from 'components/Navi'
export {default as Review} from 'components/Review'